### ISSUE TITLE
Elktail doesn't work with elasticsearch 5

### ISSUE THREAD

**Issue by timwsuqld** [knes1/elktail#13]
```bash
./elktail -ssh elasticsearch.host
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x40aa7b]

goroutine 1 [running]:
panic(0x932600, 0xc82000e120)
	/usr/local/Cellar/go/1.6/libexec/src/runtime/panic.go:464 +0x3e6
main.NewSSHTunnelFromHostStrings(0xc8200bdbc0, 0x1a, 0xa5aac7, 0xe, 0x1)
	/Users/knesek/git/go-workspace/src/github.io/knes1/elktail/sshtunnel.go:109 +0xa9b
main.main.func1(0xc820077680)
	/Users/knesek/git/go-workspace/src/github.io/knes1/elktail/elktail.go:378 +0x958
github.com/codegangsta/cli.(*App).Run(0xc820077560, 0xc82000a270, 0x3, 0x3, 0x0, 0x0)
	/Users/knesek/git/go-workspace/src/github.com/codegangsta/cli/app.go:180 +0x104c
main.main()
	/Users/knesek/git/go-workspace/src/github.io/knes1/elktail/elktail.go:424 +0x16f
```

Downloaded binary from releases, -ssh doesn't work.

Running on Ubuntu 16.04

Attempting to run elktalk on the ES node itself gives an error about not being able to connect either, but a curl works.
```
ERROR: Could not connect Elasticsearch client to http://127.0.0.1:9200: no Elasticsearch node available.
```

```
# curl 127.0.0.1:9200
{
  "name" : "suq-elastic2",
  "cluster_name" : "suq-es-1",
  "cluster_uuid" : "XXXXXXXX",
  "version" : {
    "number" : "5.0.0",
    "build_hash" : "253032b",
    "build_date" : "2016-10-26T05:11:34.737Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.0"
  },
  "tagline" : "You Know, for Search"
}
```

**Comment by knes1** [comment]
Thanks for the report. Do older versions work for you (your report implies that only v0.1.5 doesn't work)? 

As for the second issue where it doesn't work for you locally on the server, could you run it with --v3 flag and paste the output? Please note that if you are using http authentication, the output may contain your password; in that case do not post it here.

Also, I see that you are running elastic 5.0. While I was working on a separate issue I noticed threre seem to be many API changes. It's possible that EL client library that elktail uses will need to be upgraded. I experiment with it and report back.

**Comment by timwsuqld** [comment]
No luck with older versions either, same crash via SSH, and same inability to connect when on the node

``` bash
$ ./elktail -v
elktail version 0.1.3
$ ./elktail --v3
INFO: elktail.go:234: Failed to find or open previous default configuration: open /home/admin-timw/.elktail/default.json: no such file or directory
TRACE: elktail.go:288: Not saving query terms. Total terms: 0
ERROR: elktail.go:72: Could not connect Elasticsearch client to http://127.0.0.1:9200: no Elasticsearch node available.
$ curl 127.0.0.1:9200
{
  "name" : "suq-elastic2",
  "cluster_name" : "suq-es-1",
  "cluster_uuid" : "XXXXX",
  "version" : {
    "number" : "5.0.0",
    "build_hash" : "253032b",
    "build_date" : "2016-10-26T05:11:34.737Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.0"
  },
  "tagline" : "You Know, for Search"
}
$ ./elktail -v
elktail version 0.1.5
$ ./elktail -v3
INFO: elktail.go:345: Failed to find or open previous default configuration: open /home/admin-timw/.elktail/default.json: no such file or directory
TRACE: elktail.go:404: Not saving query terms. Total terms: 0
ERROR: elktail.go:81: Could not connect Elasticsearch client to http://127.0.0.1:9200: no Elasticsearch node available.

```

**Comment by knes1** [comment]
Ok - connecting to the node problem seems to be the issue with with the elasic client library elkatail currently uses to connect to elasticsearch and fact that elasticsearch 5.0 apparently introduced breaking API changes. Unfortunately, new version of the library is also not backward compatible with older versions of elasticsearch. I will need to investigate how to add support for 5.0 while also keeping compatibility with older versions.

**Comment by knes1** [comment]
As for ssh - could you please try adding your ssh username to the host and reporting back the results.

E.g. try running following:
`elktail -v3 -ssh  username@elasticsearch.host`

I suspect that elktail fails to detect your current username for some reason.

**Comment by knes1** [comment]
I have created new issue to track SSH problem: #14

**Comment by harobed** [comment]
Same issue here:

```
# curl http://127.0.0.1:9200
{
  "name" : "Bi1yAbQ",
  "cluster_name" : "log",
  "cluster_uuid" : "uZs7KrzCQ7CfrhqoFdTpWQ",
  "version" : {
    "number" : "5.0.2",
    "build_hash" : "f6b4951",
    "build_date" : "2016-11-24T10:07:18.101Z",
    "build_snapshot" : false,
    "lucene_version" : "6.2.1"
  },
  "tagline" : "You Know, for Search"
}
```

```
# elktail --v3 --url http://localhost:9200
TRACE: elktail.go:404: Not saving query terms. Total terms: 0
ERROR: elktail.go:81: Could not connect Elasticsearch client to http://localhost:9200: no Elasticsearch node available.
```

**Comment by harobed** [comment]
Maybe the error is here: https://github.com/knes1/elktail/blob/master/elktail.go#L11

**Comment by Raboo** [comment]
From a command line perspective it could perhaps be solved with options for different api versions, 
-api5 for es5, -api4.. something like that.

**Comment by knes1** [comment]
Well yes, however the difficult part is how to switch golang elastic client libraries at runtime. I would need to build some sort of abstraction layer over the client library, use that in main elktail logic, and then switch implementations depending on elastic search version (or commandline flags given).

I'm open to suggestions on what's the easiest approach to do that.

**Comment by aarishramesh** [comment]
Getting the same error. My Elastic version is 5.2.2

ERROR: Could not connect Elasticsearch client to http://127.0.0.1:9200: no Elasticsearch node available.

Is there any way I can get elk working with this elastic search version ?

**Comment by knes1** [comment]
For now, there's a fork which works with version 5: https://github.com/mnbbrown/elktail
I started work to create one version of elktail that would work with all versions of elastic, however it's proving to be challenging. Now I'm changing the decision and there will be most likely 2 versions elktail soon. One for elastic versions <=2 and one for elastic versions >2.

**Comment by xamox** [comment]
@knes1 Any thoughts as to maybe just keeping the changes in something like a esv5 branch instead of in a fork just to keep things somewhat consolidated?

**Comment by knes1** [comment]
Yes. I was researching if it would be possible to create an abstraction layer over ES client library, since we're not really using that many different APIs from Elasticsearch in order to provide elktail functionallity. Then we could have a single release that works with all elasticsearches. I was working on this but, unfortunately, my golang-fu is not good enough and I've haven't succeeded.

So basically we could do the following:

1) Update elktail to track the latest elasticseach version (that would be 5.X now)
2) As soon as Elasticsearch team introduces breaking API change that affects elktail, we move elktail to track latest elasticsearch, create a branch for older versions and maybe use http://labix.org/gopkg.in to allow people to easily fetch older versions with `go get`.

I'll do my best to set this up this weekend.

But anyhow, you're right, we should probably at least keep the v5 version in a separate branch. I'll look into that now.

**Comment by knes1** [comment]
Ok there's now a branch esv5 with merged pull request for upgrade of client library to v5. I'll keep this issue open until I setup proper versioning as described in previous post.

**Comment by xamox** [comment]
@knes1 Totally understand trying to abstract it is a pain as I've ran an open source project myself before which was based on OpenCV and when they changed from version 2 to 3 (as well as python 2 to 3) it was too much of a pain to keep up with both.  Don't feel like you need to spend your weekends getting something in quick, I was just more concerned with keeping it centralized.  Or maybe even a flag option is possible `elktail --api=5 http://myelk.com:9200`, where it could switch codebases (maybe defaults to 2 or 5, or even stored ~/.elktail/default.json).  I have about zero go language programming in my toolbelt so apologies if that would be too much of a pain.

Also thanks for writing this tool, as an ops guy it has made it super useful to just look at logs from a server without having to fire up kibana.

**Comment by rorysavage77** [comment]
This is such a shame this is not working yet.  

  ᐅ curl <hidden>:9200
{
  "name" : "red",
  "cluster_name" : "elk-yourself",
  "cluster_uuid" : "lGalAa6VReqzDT-aCWT6-A",
  "version" : {
    "number" : "5.4.0",
    "build_hash" : "780f8c4",
    "build_date" : "2017-04-28T17:43:27.229Z",
    "build_snapshot" : false,
    "lucene_version" : "6.5.0"
  },
  "tagline" : "You Know, for Search"
}
~/pi  ᐅ elktail --url host:9200
ERROR: Could not connect Elasticsearch client to http://host:9200: no Elasticsearch node available.

**Comment by Raboo** [comment]
@rcsavage perhaps you didn't read this issue?
There is a esv5 branch that works with elasticsearch v5.

**Comment by timwsuqld** [comment]
@knes1 Any chance of building binaries for the esv5 branch?

**Comment by knes1** [comment]
Ok, I decided to the following:
- Created v5 branch which uses olivere/elastic.v5 client library and should work ES 5+
- Created v1 branch which uses olivere/elastic.v2 client library and should work <= ES 2
- Changed the versioning scheme so that the major version reflects compatibility with ES
- Master branch will follow the latest version - in this case v5
- Created builds for v5 and v1 
- Updated README to reflect those changes

@timwsuqld @rcsavage  Could you please test new binaries and report here? (I currently don't have a good way to test against new versions of ES).

**Comment by timwsuqld** [comment]
@knes1 Thanks heaps for that. My quick test of the latest binary for v5 is that it works! :+1:
Much appreciated

**Comment by xamox** [comment]
Tested with v5 and working,  thanks for getting this merged in!

**Comment by rorysavage77** [comment]
It works!

**Comment by knes1** [comment]
Ok, thanks for suggestions and help with testing everyone!
